# LLaDA2-mini-DMax Math OPUT (block_size=32, buffer_size=2)
model:
  config_path: mbd_lm/configs/model_configs/llada2_mini
  model_path: ckpts/Zigeng/DMax-Math-16B-convert
  tokenizer_path: ckpts/Zigeng/DMax-Math-16B-convert
  attn_implementation: flex_attention
  moe_implementation: fused
data:
  train_path: dataset/llada2_math_multi_tf_60k_oput.jsonl
  data_type: conversation
  datasets_type: mapping
  dataloader_type: native
  max_seq_len: 2048
  text_keys: messages
  noise_range_dict:
    low_min: 0.001
    low_max: 0.3
    high_min: 0.5
    high_max: 1.0
  num_workers: 16
  buffer_size: 2
  noise_transition_margin_ratio: 0.01
  noise_transition_gamma: 2.0
  buffer_internal_ramp: chain_uniform
  explicit_block1_noise_min: 0.001
  explicit_block1_noise_max: 0.20
  explicit_block2_noise_min: 0.80
  explicit_block2_noise_max: 1.0
  noise_schedule_mode: buffer_ramp
  coverage_enable: true
  coverage_mode: full
  coverage_random_n: 0
train:
  output_dir: mbd_lm/multibd_ckpt/llada2_dmax_multi_tf_oput_math_b32
  data_parallel_mode: fsdp2
  tensor_parallel_size: 1
  ulysses_parallel_size: 1
  expert_parallel_size: 1
  global_batch_size: 32
  micro_batch_size: 1
  num_train_epochs: 4
  rmpad: false
  rmpad_with_pos_ids: false
  bsz_warmup_ratio: 0.007
  dyn_bsz_margin: 0
  dyn_bsz_buffer_size: 200
  optimizer: adamw
  beta1: 0.9
  beta2: 0.999
  lr: 2.0e-6
  lr_warmup_ratio: 0.03
  lr_decay_style: cosine
  lr_decay_ratio: 1.0
  weight_decay: 0.01
  max_grad_norm: 1.0
  enable_mixed_precision: true
  enable_gradient_checkpointing: true
  enable_full_shard: true
  enable_fsdp_offload: true
  enable_activation_offload: false
  init_device: meta
  broadcast_model_weights_from_rank0: true
  enable_full_determinism: false
  empty_cache_steps: 500
  ckpt_manager: dcp
  load_checkpoint_path: ""
  save_epochs: 1
  save_steps: 2000
  save_hf_weights: true
  save_hf_weights_per_epoch: false
  dual_bd_mode: true
  block_diffusion_mode: false
  block_size: 32
  same_token_labels: true
  ce_weight: 1.0
  kl_weight: 0.0
  use_distill: false
  wandb_online: false
  use_wandb: true
  wandb_project: MBD-LM
  wandb_name: llada2_dmax_multi_tf_oput_math_b32
  log_steps: 10
  early_stopping_enabled: false
  early_stopping_min_steps: 2000
  early_stopping_patience: 200
  early_stopping_rise_ratio: 0.08
  early_stopping_rise_window: 100
  early_stopping_stagnation_steps: 80
  early_stopping_stagnation_tol_ratio: 0.002
  loss_weight_schedule_ce: false
  loss_weight_schedule_kl: false
  loss_weight_schedule_warmup_steps: 100
  loss_weight_schedule_hold_steps: 500
  loss_weight_schedule_decay_ratio: 0.5
  loss_weight_schedule_decay_steps: 1000
  loss_weight_schedule_normalize: true
  loss_weight_schedule_style: fix_then_balance
  loss_weight_schedule_fix_steps: 500
  loss_weight_schedule_ema_momentum: 0.9
