# SDAR-8B-Chat-b4 Code MultiTF CE (block_size=4, buffer_size=4)
model:
  config_path: mbd_lm/configs/model_configs/sdar_8B
  model_path: ckpts/JetLM/SDAR-8B-Chat
  student_model_path: ckpts/JetLM/SDAR-8B-Chat
  tokenizer_path: ckpts/JetLM/SDAR-8B-Chat
  attn_implementation: flex_attention
data:
  train_path: dataset/sdar_code_multi_tf_10k.jsonl
  data_type: conversation
  datasets_type: mapping
  dataloader_type: native
  max_seq_len: 2048
  text_keys: messages
  noise_range_dict:
    low_min: 0.001
    low_max: 0.3
    high_min: 0.5
    high_max: 1.0
  num_workers: 16
  buffer_size: 4
  noise_transition_margin_ratio: 0.01
  noise_transition_gamma: 2.0
  buffer_internal_ramp: chain_uniform
  noise_schedule_mode: buffer_ramp
  coverage_enable: true
  coverage_random_n: 2
train:
  output_dir: mbd_lm/multibd_ckpt/sdar_multi_tf_code_b4
  data_parallel_mode: fsdp2
  tensor_parallel_size: 1
  ulysses_parallel_size: 1
  expert_parallel_size: 1
  global_batch_size: 32
  micro_batch_size: 1
  num_train_epochs: 2
  rmpad: false
  rmpad_with_pos_ids: false
  bsz_warmup_ratio: 0.007
  dyn_bsz_margin: 0
  dyn_bsz_buffer_size: 200
  optimizer: adamw
  beta1: 0.9
  beta2: 0.999
  lr: 1.0e-5
  lr_warmup_ratio: 0.03
  lr_decay_style: cosine
  lr_decay_ratio: 1.0
  weight_decay: 0.1
  max_grad_norm: 1.0
  enable_mixed_precision: true
  enable_gradient_checkpointing: true
  enable_full_shard: true
  enable_fsdp_offload: true
  enable_activation_offload: false
  init_device: meta
  broadcast_model_weights_from_rank0: true
  enable_full_determinism: false
  empty_cache_steps: 500
  ckpt_manager: dcp
  load_checkpoint_path: ""
  save_epochs: 1
  save_steps: 200
  save_hf_weights: true
  save_hf_weights_per_epoch: false
  block_size: 4
  block_size_teacher: 4
  same_token_labels: true
  use_distill: false
  student_mask_mode: buffer_multi_bd
  kl_temperature_teacher_start: 1.0
  kl_temperature_teacher_end: 1.0
  teacher_temperature_schedule_style: fixed
  kl_temperature_student_fixed: 1.0
  ce_weight: 1.0
  kl_weight: 0.0
  normalize_loss_weights: false
  wandb_online: false
  use_wandb: true
  wandb_project: MBD-LM
  wandb_name: sdar_multi_tf_code_b4
  log_steps: 10
